"use strict";
exports.INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
exports.DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';
exports.LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
exports.LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
exports.LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';
exports.LOGOUT_USER = 'App/LOGOUT_USER';
exports.FORM_RESET = 'redux-form/RESET';
//# sourceMappingURL=index.js.map